before_script:
  - apt update && apt install -y openjdk-17-jdk
  - chmod +x ./gradlew
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ./gradlew clean build

unit-test-job:
  stage: test
  script:
    - ./gradlew test